INSERT INTO CATEGORY(ID, NAME) VALUES(1, 'Alimentos');
INSERT INTO CATEGORY(ID, NAME) VALUES(2, 'Eletrodomésticos');
INSERT INTO CATEGORY(ID, NAME) VALUES(3, 'Móveis');

INSERT INTO PRODUCT(ID, NAME, IDCATEGORY) VALUES(1, 'Arroz', 1);
INSERT INTO PRODUCT(ID, NAME, IDCATEGORY) VALUES(2, 'Feijão', 1);

INSERT INTO PRODUCT(ID, NAME, IDCATEGORY) VALUES(3, 'Aspirador de pó', 2);
INSERT INTO PRODUCT(ID, NAME, IDCATEGORY) VALUES(4, 'Batedeira', 2);
INSERT INTO PRODUCT(ID, NAME, IDCATEGORY) VALUES(5, 'Liquidificador', 2);

INSERT INTO PRODUCT(ID, NAME, IDCATEGORY) VALUES(6, 'Sofá', 3);
INSERT INTO PRODUCT(ID, NAME, IDCATEGORY) VALUES(7, 'Mesa', 3);
INSERT INTO PRODUCT(ID, NAME, IDCATEGORY) VALUES(8, 'Estante', 3);